//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Questionnaire.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuestionnaireDBContext : DbContext
    {
        public QuestionnaireDBContext()
            : base("name=QuestionnaireDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DropDownValues> DropDownValues { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<QuestionnaireMaster> QuestionnaireMaster { get; set; }
        public virtual DbSet<QuestionType> QuestionType { get; set; }
        public virtual DbSet<Report> Report { get; set; }
        public virtual DbSet<ReportMaster> ReportMaster { get; set; }
    
        public virtual ObjectResult<Nullable<int>> DeleteQuestion(Nullable<int> questionID)
        {
            var questionIDParameter = questionID.HasValue ?
                new ObjectParameter("QuestionID", questionID) :
                new ObjectParameter("QuestionID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("DeleteQuestion", questionIDParameter);
        }
    }
}
