//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Questionnaire.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuestionnaireDBContext : DbContext
    {
        public QuestionnaireDBContext()
            : base("name=QuestionnaireDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DropDownValues> DropDownValues { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<QuestionnaireMaster> QuestionnaireMaster { get; set; }
        public virtual DbSet<QuestionType> QuestionType { get; set; }
    }
}
