//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Questionnaire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.DropDownValues = new HashSet<DropDownValues>();
        }
    
        public int ID { get; set; }
        public int QuestionnaireID { get; set; }
        public int QuestionType { get; set; }
        public int Hierarchy { get; set; }
        public string QuesText { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DropDownValues> DropDownValues { get; set; }
        public virtual QuestionnaireMaster QuestionnaireMaster { get; set; }
        public virtual QuestionType QuestionType1 { get; set; }
    }
}
