//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Questionnaire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ID { get; set; }
        public System.Guid ReportID { get; set; }
        public int Heirarchy { get; set; }
        public string Text { get; set; }
        public string Response { get; set; }
    
        public virtual ReportMaster ReportMaster { get; set; }
    }
}
