namespace Questionnaire.HTMLBuilder
{
    public static class HtmlSkeleton
    {
        public static string BooleanHtml { get; } = "<div class=\"row QuestionRow BooleanQuestion\"> <div class=\"text-primary QuestionNumber\">{0}</div><div class=\"col-sm-11 QuestionPanel\"> <div class=\"row\">{1}</div><div class=\"row col-sm-12 InputPanel\"> <div class=\"pull-right\"> <div class=\"btn-group-sm\" data-toggle=\"buttons\"> <label id=\"op1-{2}\" class=\"btn btn-default radiobtn active\"> <input type=\"radio\" autocomplete=\"off\" checked> Yes </label> <label id=\"op2-{3}\" class=\"btn btn-default radiobtn\"> <input type=\"radio\" name=\"options\" autocomplete=\"off\"> No </label> <label id=\"op3-{4}\"class=\"btn btn-default radiobtn\"> <input type=\"radio\" name=\"options\" autocomplete=\"off\"> N.A. </label> </div></div></div></div></div>";
        public static string DropDownHtml { get; } = "<div class=\"row QuestionRow DropDownQuestion\"> <div class=\"text-primary QuestionNumber\">{0}</div><div class=\"col-sm-11 QuestionPanel\"> <div class=\"row\">{1}</div><div class=\"row col-sm-12 InputPanel\"> <div class=\"pull-right\"> <select class=\"form-control DropDownControl\">{2}</select> </div></div></div></div>";
        public static string DropDownItemHtml { get; } = "<option id=\"ch{0}-{1}\" value=\"{2}\">{3}</option>";
        public static string FreeTextHtml { get; } = "<div class=\"row QuestionRow FreeTextQuestion\"> <div class=\"text-primary QuestionNumber\">{0}</div><div class=\"col-sm-11 QuestionPanel\"> <div class=\"row\">{1}</div><div class=\"row col-sm-12 InputPanel\"> <div class=\"col-sm-offset-4 col-sm-8\" style=\"padding: 0;\"> <input id=\"freeTxt-{2}\" class=\"form-control userTextInput\" type=\"text\"/> </div></div></div></div>";
        public static string DatePickerHtml { get; } = "<div class=\"row QuestionRow FreeTextQuestion\"> <div class=\"text-primary QuestionNumber\">{0}</div><div class=\"col-sm-11 QuestionPanel\"> <div class=\"row\">{1}</div><div class=\"row col-sm-12 InputPanel\"> <div class=\"col-sm-offset-9 col-sm-3\" style=\"padding: 0;\"> <div class=\"input-group date\"> <input id=\"freeTxt-{2}\" type=\"text\" class=\"form-control userTextInput\" placeholder=\"MM/DD/YYYY\"/> <span class=\"input-group-addon\"> <i class=\"fa fa-calendar\"></i> </span> </div></div></div></div></div>";
        public static string NumericHtml { get; } = "<div class=\"row QuestionRow FreeTextQuestion\"> <div class=\"text-primary QuestionNumber\">{0}</div><div class=\"col-sm-11 QuestionPanel\"> <div class=\"row\">{1}</div><div class=\"row col-sm-12 InputPanel\"> <div class=\"col-sm-offset-9 col-sm-3\" style=\"padding: 0;\"> <input id=\"freeTxt-{2}\" name=\"freeTxt-{3}\" class=\"form-control userTextInput num\" type=\"text\"/> </div></div></div></div>";
        public static string InstructionHtml { get; } = "<div class=\"row InstructionMsg\"> <div class=\"col-sm-12\"> <div id=\"instructTxt-{1}\"  class=\"text instructDiv text-info\">{0}</div></div></div>";
    }
}